FROM node:20 AS build
WORKDIR /app
COPY package*.json ./

RUN npm install

COPY . .

RUN echo "$FRONTEND_ENV" > .env

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]