FROM node:20 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
COPY .env.frontend .env
RUN npm run build

FROM nginx:alpine AS prod

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

VOLUME [ "/etc/letsencrypt" ]

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
