FROM node:20 AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY . .

COPY .env.prod .env

ENV NODE_OPTIONS="--max-old-space-size=4096"  # 4GB

RUN npm run build

FROM nginx:alpine AS prod

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf

COPY ./ssl /etc/nginx/ssl

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]