name: Deploy Frontend

on:
  workflow_run:
    workflows: ['Build and Test Frontend']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH key for VPS
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/tickets-pair.pem
          chmod 600 ~/.ssh/tickets-pair.pem
          ssh-keyscan -H ec2-18-206-225-209.compute-1.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          scp -i ~/.ssh/tickets-pair.pem -o StrictHostKeyChecking=no -r ./dist/ ubuntu@ec2-18-206-225-209.compute-1.amazonaws.com:/project/tickets_frontend
          ssh -i ~/.ssh/tickets-pair.pem -o StrictHostKeyChecking=no ubuntu@ec2-18-206-225-209.compute-1.amazonaws.com "cd project && docker-compose up -d"
