name: Deploy Frontend

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      FRONTEND_ENV: ${{ secrets.FRONTEND_ENV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_LOGIN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/andreyfaichuk/tickets-frontend:latest -f Dockerfile.prod .
          docker push ghcr.io/andreyfaichuk/tickets-frontend:latest

      - name: Setup SSH key for VPS
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/tickets-pair.pem
          chmod 600 ~/.ssh/tickets-pair.pem
          ssh-keyscan -t rsa -H ec2-18-214-91-17.compute-1.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-214-91-17.compute-1.amazonaws.com << 'EOF'
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
            cd /home/ubuntu/project
            docker-compose pull
            docker-compose up -d --remove-orphans
          EOF
