name: Deploy Frontend

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/username/tickets-frontend:latest -f Dockerfile.prod .
          docker push ghcr.io/username/tickets-frontend:latest

      - name: Deploy to VPS
        run: |
          ssh -i ~/.ssh/tickets-pair.pem -o IdentitiesOnly=yes ubuntu@ec2-18-214-91-17.compute-1.amazonaws.com << 'EOF'
            docker pull ghcr.io/username/tickets-frontend:latest
            docker-compose up -d --no-deps tickets_frontend_prod tickets_backend_prod
          EOF
